name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYED_FILES: /var/finance/deployed

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn rebuild
      - run: yarn build

      - name: Run release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          git clone --branch static-site https://${GH_TOKEN}@github.com/faustt/apps /tmp/apps
          sudo mkdir -p /tmp/apps/public/todo
          sudo cp -a ./dist/. /tmp/apps/public/todo/
          cd /tmp/apps
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "[automated] Update todo artifacts"
          git push origin
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          APP_BASE_PATH: todo
