name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOYED_FILES: /var/finance/deployed

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: yarn rebuild
      # - run: yarn test
      - run: yarn build

      - name: Run release
        run: yarn dlx @faustt/release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          sudo mkdir -p $DEPLOYED_FILES
          sudo cp -a ./dist/. $DEPLOYED_FILES/
      - run: git switch --orphan static-website
      - run: ls -lah
      - run: |
          sudo rm -rf ./*
          sudo rm -rf ./.yarn
      - run: ls -lah
      - run: sudo cp -a $DEPLOYED_FILES/. ./

      - run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "[automated] Update static artifacts"
          git push origin static-website --force
